server:
  port: 20003
  servlet:
    context-path: /consul-foo
spring:
  cloud:
    consul:
      discovery:
        healthCheckPath: /consul-foo/actuator/health
        healthCheckInterval: 2s
        instanceId: ${spring.application.name}:${random.int(100,500)}

